[package]
name = "hello-world-container-lambda"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "checkerboard"
path = "src/handlers/checkerboard.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
